[package]
name = "sf-ope-client"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
chacha20poly1305 = "0.10.1"
rand = "0.8.5"

[dependencies.sf-ope-commons]
path = "../sf-ope-commons"